[language-server.mylang-lsp]
command = "mylang-lsp"



[[language]]
name = "ada"
scope = "source.ada"
file-types = ["adb", "ads"]
comment-token = "--"
indent = { tab-width = 2, unit = " " }

[language-server]
ada-language-server = { command = "ada_language_server" }
ada-gpr-language-server = { command = "ada_language_server", args = ["--language-gpr"] }

