theme = "nyxvamp-obsidian"
#theme = "iroaseta"
[editor]
line-number = "relative"
mouse = false
clipboard-provider = "wayland"
[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
[editor.file-picker]
hidden = true


[keys.normal]
"\\" = "file_picker_in_current_buffer_directory"
