
# BlackMetal by metalelf0 — Alacritty port
# Source: https://github.com/metalelf0
# License: MIT

[colors.primary]
background = "#000000"
foreground = "#ffffff"

[colors.selection]
background = "#ffffff"
text       = "#000000"

[colors.cursor]
cursor = "#ffffff"
text   = "#000000"

[colors.normal]
black   = "#000000"  # color0
red     = "#5f8787"  # color1
green   = "#dd9999"  # color2
yellow  = "#a06666"  # color3
blue    = "#888888"  # color4
magenta = "#999999"  # color5
cyan    = "#aaaaaa"  # color6
white   = "#c1c1c1"  # color7

[colors.bright]
black   = "#333333"  # color8
red     = "#5f8787"  # color9
green   = "#dd9999"  # color10
yellow  = "#a06666"  # color11
blue    = "#888888"  # color12
magenta = "#999999"  # color13
cyan    = "#aaaaaa"  # color14
white   = "#c1c1c1"  # color15

